name: CI/CD - Snakes and Ladders

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [BackEnd, FrontEnd]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./${{ matrix.project }}

      - name: Build
        run: dotnet build ./${{ matrix.project }} --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./Tests --no-build --verbosity normal

  deploy:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🐍 Backend Docker image
      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/snl-backend:latest ./BackEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/snl-backend:latest

      # 🎮 Frontend Docker image
      - name: Build and push Frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/snl-frontend:latest ./FrontEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/snl-frontend:latest

