name: CI/CD - Snakes and Ladders

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [BackEnd, FrontEnd]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # ✅ Navigate into each project folder before restoring/building
      - name: Restore dependencies
        working-directory: ${{ matrix.project }}
        run: dotnet restore

      - name: Build project
        working-directory: ${{ matrix.project }}
        run: dotnet build --configuration Release --no-restore

      # ✅ Adjust this to your actual test folder name
      - name: Run tests
        run: dotnet test SnakesAndLadders.Tests --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/snl-backend:latest BackEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/snl-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/snl-frontend:latest FrontEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/snl-frontend:latest
